name: Site

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true
        env:
          BUNDLE_GEMFILE: site/Gemfile
      - uses: actions/configure-pages@v2
        id: pages
      - name: Build
        run: |
          cd site
          bundle exec jekyll \
            build \
            --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y -V \
            ccache \
            gi-docgen \
            libev-dev \
            libgirepository1.0-dev \
            meson
          sudo gem install gio2
      - name: Cache ccache
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: site-ccache-${{ hashFiles('libmilter/**', 'milter/**', 'src/**', 'tool/**', 'test/**') }}
          restore-keys: site-ccache-
      - name: Setup
        run: |
          meson setup \
            --prefix=/tmp/local \
            -Ddoc=true \
            ../milter-manager.build \
            .
      - name: Build
        run: |
          meson compile -C ../milter-manager.build
      - name: Install
        run: |
          sudo meson install -C ../milter-manager.build
      - name: Move reference manuals
        run: |
          mkdir -p site/_site/reference/
          mv \
            /tmp/local/share/doc/milter-manager/* \
            site/_site/reference/
      - uses: actions/upload-pages-artifact@v1

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment
