name: Site

on:
  push:
    branches:
      - master

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger
        run: |
          gh workflow \
            --repo milter-manager/milter-manager.github.io \
            run \
            site.yml \
            --raw-field source-reference=master
