name: Test
on:
  - push
  - pull_request
jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
          - ubuntu-24.04-arm
        service:
          - almalinux-8
          - almalinux-9
          - almalinux-10
          - debian-bullseye
          - debian-bookworm
          - debian-trixie
          - ubuntu-jammy
    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5
      - name: Install dependencies
        if: ${{ matrix.runs-on == 'ubuntu-latest' }}
        run: |
          sudo apt update
          sudo apt install -y -V \
            curl \
            gtk-doc-tools \
            intltool \
            lsb-release
          curl \
            --silent \
            --location \
            https://raw.github.com/clear-code/cutter/master/data/travis/setup.sh | sh
      - name: Install dependencies
        if: ${{ matrix.runs-on != 'ubuntu-latest' }}
        run: |
          sudo apt update
          sudo apt install -y -V \
            curl \
            gtk-doc-tools \
            intltool \
            lsb-release \
            libglib2.0-dev
      - run: ./autogen.sh
      - run: docker compose build ${{ matrix.service }}
      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: .cache/ccache
          key: test-${{ matrix.service }}-ccache-${{ hashFiles('libmilter/**', 'milter/**', 'src/**', 'tool/**', 'test/**') }}
          restore-keys: test-${{ matrix.runs-on }}-${{ matrix.service }}-ccache-
      - name: Prepare ccache directory
        run: |
          sudo mkdir -p .cache/ccache/
          sudo chmod -R o+rwx .cache/ccache/
      - name: Run
        run: |
          docker compose run --rm \
            --env USE_CUTTER=${{ matrix.runs-on == 'ubuntu-latest' }} \
            ${{ matrix.service }}

  # Temporary. We should integrate this to the above test job.
  meson:
    name: meson
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y -V \
            ccache \
            libev-dev \
            libgirepository1.0-dev \
            meson
          sudo gem install gio2
      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: test-meson-ccache-${{ hashFiles('libmilter/**', 'milter/**', 'src/**', 'tool/**', 'test/**') }}
          restore-keys: test-meson-${{ matrix.runs-on }}-ccache-
      - name: Setup
        run: |
          meson setup \
            --prefix=/tmp/local \
            ../milter-manager.build \
            .
      - name: Build
        run: |
          meson compile -C ../milter-manager.build
      - name: Install
        run: |
          sudo meson install -C ../milter-manager.build
      - name: Test
        # TODO: Remove this
        continue-on-error: true
        run: |
          meson devenv -C ../milter-manager.build \
            meson test \
              --print-errorlogs \
              --verbose
